Update: read only modules
p2pcommons/sdk-js pull request #210
Opened 2020-08-12 17:34 UTC by dpaez

This PR introduces `read-only` permission only for **versioned** modules.  

Closes #172

2020-08-12 17:48 UTC, dpaez commented
Looks like its failing only on windows. Would need to dig more into this.

2020-08-12 21:07 UTC, chartgerink commented
Code looks good to me from my reading levels 😊 

Here's the error from the log, which isn't particularly helpful either.

```
    × cloned module is writable
    ----------------------------
      operator: fail
      at: Test.<anonymous> (D:\a\sdk-js\sdk-js\tests\index.js:1769:7)
      stack: |-
  Error: cloned module is writable
  at Test.assert [as _assert] (D:\a\sdk-js\sdk-js\node_modules\tape\lib\test.js:228:54)
  at Test.bound [as _assert] (D:\a\sdk-js\sdk-js\node_modules\tape\lib\test.js:80:32)
  at Test.fail (D:\a\sdk-js\sdk-js\node_modules\tape\lib\test.js:322:10)
  at Test.bound [as fail] (D:\a\sdk-js\sdk-js\node_modules\tape\lib\test.js:80:32)
  at Test.<anonymous> (D:\a\sdk-js\sdk-js\tests\index.js:1769:7)
```

Might it be that because Windows is not UNIX based it has different file ownership rules and `chmodr` doesn't work the same there? (long shot)

2020-08-17 08:29 UTC, juliangruber commented on README.md
> +:warning: NOTE: **versioned** modules directories are `read-only`.
```suggestion
:warning: NOTE: **versioned** module directories are `read-only`.
```

double plural

2020-08-17 08:30 UTC, juliangruber commented on index.js
> +        }
what if any error happens afterwards? should we use a try/catch/finally here, so that even if an error happens it will be made read only afterwards?

2020-08-17 08:31 UTC, juliangruber commented on index.js
> +      return
why abort here? if the dir isn't accessible, that's an error, right?

2020-08-17 08:32 UTC, juliangruber commented on index.js
> +    const permString = '0' + (stat.mode & 0o777).toString(8)
could you add a comment here?

2020-08-17 08:33 UTC, juliangruber commented on index.js
> +        // make moduleDir writable first
I'm not sure I follow the logic. In my understanding, the dir `${key}` is always writable, and the dirs `${key}+${version}` are never writable. Isn't that true?

2020-08-17 08:34 UTC, juliangruber commented on index.js
> +    const permString = stat.mode & 0o777
could you add a comment for this too?

2020-08-18 07:00 UTC, chartgerink commented on index.js
> +        // make moduleDir writable first
`${key}` might not be writable if the Hyperdrive is somebody else's?

2020-08-18 07:42 UTC, juliangruber commented on index.js
> +        // make moduleDir writable first
ah gotcha, but the PR description says `This PR introduces read-only permission only for versioned modules.`

2020-08-18 08:06 UTC, chartgerink commented on index.js
> +        // make moduleDir writable first
Oh sorry! You're right 🙈 Also part of my own comment https://github.com/p2pcommons/sdk-js/issues/172#issuecomment-671973715

2020-08-19 08:16 UTC, juliangruber requested changes
needs a rebase

2020-08-19 14:18 UTC, dpaez commented
rebased cc @juliangruber

2020-08-19 14:33 UTC, juliangruber commented
the files changed tab still shows changes from another PR that aren't yet in master :/

2020-08-19 18:32 UTC, dpaez commented
> the files changed tab still shows changes from another PR that aren't yet in master :/

I double checked the Commits and Files changed tabs and everything looks related to this update. Maybe I'm a bit lost here.

2020-08-20 18:59 UTC, dpaez commented
I think this needs a new rebase now 😓

2020-08-20 20:03 UTC, dpaez commented
Rebased and fixed! :)

2020-08-21 07:26 UTC, juliangruber commented on index.js
> +            await this.makeWrite(moduleDir)
maybe `makeWritable` is more obvious to the reader

2020-08-21 07:27 UTC, juliangruber commented on index.js
> +              dlHandle.on('end', () => this.makeReadOnly(moduleDir))
errors thrown from `this.makeReadOnly` can't be caught, what about using the `once` function again?

2020-08-21 07:27 UTC, juliangruber commented on index.js
> +      this._log(err.message, 'warn')
why log the error if we also throw it? I think this try/catch could just be removed

2020-08-21 07:27 UTC, juliangruber commented on index.js
> +    }
same here as above

2020-08-21 07:28 UTC, juliangruber commented on index.js
> +      if (err.code === 'EEXIST' || err.code === 'EACCES') {
```suggestion
      if (err.code === 'EEXIST' || err.code === 'EACCESS') {
```

2020-08-24 06:35 UTC, juliangruber commented on index.js
> +            await this.makeWrite(moduleDir)
To me that is fine as it is :)

2020-08-24 06:41 UTC, juliangruber requested changes

2020-08-24 06:41 UTC, juliangruber commented on index.js
> +          }
The module dir is made writable if it's not a checkout, and read only only if it is a checkout. Doesn't that mean that if it's not a check out, it doesn't need to be made writable, since it never was made read only?

2020-08-24 06:41 UTC, juliangruber commented on index.js
> +    await access(moduleDir)
Why the `access` call here? If it's not accessible, the `statFn` or `chmodr` below would throw anyways

2020-08-25 09:16 UTC, juliangruber approved these changes

2020-08-25 11:40 UTC, merged