Update: delete check access
p2pcommons/sdk-js pull request #227
Opened 2020-08-25 20:31 UTC by dpaez

This is a little tweak to `delete` method. It helps avoid a situation when `trash` call doesn't return and leaves the process frozen. This happens if we try to remove an already deleted directory. Such a situation could happen if we don't pass a versioned url on hypergraph when we want to delete already registered content, for example.

2020-08-26 06:45 UTC, juliangruber requested changes

2020-08-26 06:45 UTC, juliangruber commented on index.js
> +        } catch (err) {
this could also throw if the directory exists but permissions forbid it to be accessed

2020-08-26 06:45 UTC, juliangruber commented on index.js
> +        } catch (err) {
I just looked at the trash module's source code, and it's using synchronous file system calls.

Also it looks like the trash module already does a check like this:

https://github.com/sindresorhus/trash/blob/d6d2c3a86125925b4e04749a8e3a311af48e93b8/index.js#L34-L39

2020-08-26 06:45 UTC, juliangruber commented on index.js
> +        } catch (err) {
Do you know where the process hangs exactly?

2020-08-26 12:21 UTC, dpaez commented on index.js
> +        } catch (err) {
Hi juli :wave: Yeah, I recognise this looks like an extra thing to do. 
We saw this issue yesterday when trying hypergraph with the latest sdk that you can get from master. 

1. you create your profile
2. create and register content
3. try to delete the content

What happens next is, first time you call delete, it succeeds quickly, but you still see the content attached to the profile. So if you hit delete again, it will hang. 
I put a debugger in hypergraph right after this (https://github.com/hypergraph-xyz/desktop/blob/fe1ce6de64bf4ebafd1d8367342e4711b89f9391/app/components/content/content.js#L353) and it never reaches that point. I try the same operation with this little fix and it worked.

You are right about the permissions, If we add these line it should be moved right before the trash call. Because in the middle we already address the permission check.

2020-08-28 08:45 UTC, juliangruber commented on index.js
> +        } catch (err) {
When I try to delete a module with latest sdk-js, I see this:

![image](https://user-images.githubusercontent.com/10247/91540800-9caa0b80-e91b-11ea-80e2-181b4e1aef78.png)

2020-08-28 15:24 UTC, dpaez commented on index.js
> +        } catch (err) {
I'm not able to reproduce this. The only thing similar I can reproduce is, if I try to `delete` registed content and the version is not passed as part of the key to the delete method then `delete` is trying to remove the unversioned directory. And that works. But the profile is still pointing to the versioned directory. So, on the next restart of the sdk/hypergraph you will see the content there again.

2020-08-31 14:16 UTC, jameslibscie commented
@juliangruber, @dpaez and I decided that the best way to go would be as follows:
- Receives unversioned keys (otherwise error)
- Deregisters all versioned and unversioned registrations from profile
- Removes from DB
- Deletes all versioned and unversioned folders from disk

2020-09-01 06:53 UTC, juliangruber approved these changes
It works!

2020-09-01 13:26 UTC, dpaez commented
@juliangruber and @jameslibscie I've updated the PR with the deregister fixes.

2020-09-01 13:27 UTC, dpaez commented on index.js
> +        } catch (err) {
ended up removing the access call.

2020-09-02 14:18 UTC, merged