Update: improve file check using stat mtime
p2pcommons/sdk-js pull request #229
Opened 2020-08-26 22:28 UTC by dpaez

This PR attempts to fix #228 by improving how we are checking the file existence condition. Instead of just checking if there is a file with the passed _name_ we now compare file and drive stat's **mtime** for that file. This should be more robust.

Closes #228

2020-08-27 10:28 UTC, jameslibscie commented
The bug with renamed main file still exists and I've verified that it's the same cause as #228 

1. I create a new module with a file that is the main file
2. I edit that file
3. I use `get()` or `listContents()`, it returns version 5, even though I've updated a file -> this is the root cause
4. I rename the file
5. I use `get()` or `listContents()`, it returns version 5, even though I've renamed the file -> same problem again
6. I use `set()` to update the main file, but it fails, looking for the *previous* main file, which no longer exists -> new problem, which may be caused by it somehow verifying the old metadata? I'm actually not so sure about this anymore.

Either way, #228 is more about making sure that the SDK bumps the version number as soon as any file in the drive changes, as long as Hypergraph is running of course. Otherwise, we can't really reliably allow file editing at all...

2020-08-27 12:03 UTC, jameslibscie commented
If we're having a hard time getting the file changes to be seen automatically, would a good workaround perhaps be to have a `refresh(key)` method that rescans the drive, updates the DB and can be awaited before performing certain actions like register?

2020-08-27 17:47 UTC, dpaez commented
Quick update: I've been toying around an implementation that will update the local db on every 'put-end' event that is emitted by the mirror-folder watching that folder. I'm getting some false positives so I need to improve and maybe filtering some updates. 

I don't discard the possibility of having a new `sync` method also. This would work better. So I probably end up adding support for both strategies maybe or just the `sync`.

2020-08-28 01:06 UTC, dpaez commented
Added a new `sync` method AND make use of some local hooks to auto update on changes. So its not necessary to call `sync`, but in some cases, like if the user needs to do an operation that needs the latest version then calling `sync`. Eg: user modifies content, like add new files to a content module. Then immediately after wants to register that content module. In that case, having the latest version is important. We can hook and listen to the `update-content` event or just call `sync`. 

A side effect is that we are possibly incrementing the version more than once by overwriting the drive. I'm looking if there is an easy/realiable way of avoiding/filtering changes.

2020-08-28 09:17 UTC, jameslibscie commented
The versions update immediately - this is working great! Except I can't seem to get `sync()` to work a lot of the time:

![image](https://user-images.githubusercontent.com/59870484/91544435-0a583680-e920-11ea-9c66-f984f2f2f201.png)

Doesn't matter whether I `encode()` the URL or not. It did work at first though!

2020-08-28 14:56 UTC, jameslibscie commented
I was thinking about the name of `sync()` and think it might be confusing as it might suggest syncing with the network. How about `refreshDrive()`?

2020-08-28 15:06 UTC, dpaez commented
> I was thinking about the name of `sync()` and think it might be confusing as it might suggest syncing with the network. How about `refreshDrive()`?

Yeah, I like it. Also `syncDrive` and `updateDrive`.

2020-09-01 07:13 UTC, juliangruber requested changes

2020-09-01 07:13 UTC, juliangruber commented on README.md
> +> _async_ `sync(key: string|buffer, moduleDir: string, opts: object)`
What about instead of passing the `dir` we pass `key` and optionally `version`? The SDK knows enough to construct the `dir` from that.

2020-09-01 07:13 UTC, juliangruber commented on README.md
> +Synchronize an hyperdrive with a module directory. Optionally accepts an opts object. These are passed to [dft](https://github.com/pfrazee/diff-file-tree).
It would be useful to explain some more why synchronizing helps. For example, when do you need to synchronize it?

2020-09-01 07:13 UTC, juliangruber commented on index.js
> +    } catch (err) {
This try/catch makes the method decide how to handle errors, not the consumer. What about removing it here and changing the call below to

```js
this._updateLocalDB(publicKeyString, dst).catch(err => this._log(err.message, 'error'))
```

This way to me it would be clearer when reading the code.

2020-09-01 07:13 UTC, juliangruber commented on index.js
> +      this._log('drive is not writable -  can not sync')
```suggestion
      this._log('drive is not writable -  nothing to sync')
```

This makes it clearer that it's not an error at all since nothing is to be done

2020-09-01 07:14 UTC, juliangruber commented
I think this PR's name could be updated because it's now about the `sync` method

2020-09-01 08:26 UTC, jameslibscie commented on README.md
> +> _async_ `sync(key: string|buffer, moduleDir: string, opts: object)`
`sync` only makes sense on the unversioned folder as the versioned folder shouldn't be updated and wouldn't trigger a new version. I agree that it should only be the key passed.

2020-09-01 08:27 UTC, jameslibscie commented on README.md
> +Synchronize an hyperdrive with a module directory. Optionally accepts an opts object. These are passed to [dft](https://github.com/pfrazee/diff-file-tree).
```suggestion
Synchronize a hyperdrive with a module directory to ensure that the sdk is aware of the latest changes to files. Optionally accepts an opts object. These are passed to [dft](https://github.com/pfrazee/diff-file-tree).
```

2020-09-01 13:41 UTC, dpaez commented on README.md
> +> _async_ `sync(key: string|buffer, moduleDir: string, opts: object)`
going with the `key` as the only parameter

2020-09-01 14:00 UTC, dpaez commented on index.js
> +    } catch (err) {
I like it!

2020-09-02 06:11 UTC, juliangruber approved these changes
Looks great!

2020-09-02 08:42 UTC, jameslibscie requested changes
Haven't tested, but would strongly suggest renaming `sync()` to something else

2020-09-02 13:33 UTC, dpaez commented
Renamed sync method to `refreshDrive`

2020-09-03 05:53 UTC, juliangruber approved these changes

2020-09-03 08:27 UTC, jameslibscie approved these changes
Awesome!

2020-09-04 12:18 UTC, merged