Add plain text validation
p2pcommons/sdk-js pull request #233
Opened 2020-09-01 15:06 UTC by chartgerink

Added a first implementation after talking with @dpaez for issue #231. Tried adding a test but wasn't succesful at the moment.

2020-09-01 16:29 UTC, dpaez commented
@chartgerink updated! I think is good to work

2020-09-01 20:20 UTC, juliangruber requested changes

2020-09-01 20:20 UTC, juliangruber commented on lib/validate.js
> +  } catch (_) {}
what's the reason for ignoring errors here?

2020-09-02 08:11 UTC, chartgerink commented
Nice, thanks @dpaez! I see I was being too hasty by adding the path without concatenating the p2pcommons dir. The test needed a file written out I see as well, thanks for teaching me

![](https://media.giphy.com/media/fItgT774J3nWw/giphy.gif)

2020-09-02 13:48 UTC, dpaez commented on lib/validate.js
> +  } catch (_) {}
This code is part of `_validateMainExtension` function which is part of `validateMain` function. The `_validateMainExtension` runs after `_validateMainExists`, a function that checks for the existence of the main file. So we can assume that a main file should exist up to this point.

I think I wanted to be protected if the function run outside `validateMain` and/or something weird happens with readFile fn. This is connected to the fact that we are adding this double check like the extension check and the content one. If there is no `mainBuffer` for some reason, then the content check wont happen and we will end up with two possibly different validations on the extensions of the main file.  So the absence of the mainBuffer does not break things. Unless we strongly wanted to have the content validation.

2020-09-02 14:51 UTC, dpaez commented on lib/validate.js
> +  } catch (_) {}
I put some seconds thoughts on this and I think it's safe to remove that try/catch cage. Release the readFile! :)

2020-09-03 05:55 UTC, juliangruber commented on lib/validate.js
> +  } catch (_) {}
I think we kind of have to do content validation, if "it's plain text" makes it valid. Good point about _validateMainExtension being callable outside of the validateMain function, I assumed it would be private because it starts the an underscore.

2020-09-03 05:56 UTC, juliangruber requested changes

2020-09-03 11:41 UTC, dpaez commented on lib/validate.js
> +  await _validateMainExtension(indexMetadata, key, p2pcommonsDir)
I'll go with `_validateMainContentType`

2020-09-04 12:19 UTC, merged